provider:
  environment:
    LOG_LEVEL: 2
custom:
  region: "eu-west-1"
  DynamoCapacity:
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5
  NBPCurrencyUrl: 'http://api.nbp.pl/api/exchangerates/tables/C/today/'
  ZombieMarketPricesUrl: 'https://zombie-items-api.herokuapp.com/api/items'